name: Format

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  code:
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install dependencies
        uses: './.github/actions/install-deps'

      - name: Run Prettier
        run: pnpm format:check